language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python -m unittest
deploy:
  provider: heroku
  api_key:
    secure: GNcEaid6gbR5We1FvvmWoxMD86kl/VUwEb2KRhp7x94f54tMCCY2c/8D54pfJc2LH2UyVU4nMC4vO21RMZYmUHxUgHNj6pr8snf0HMp7bPCf81f29PCs5N6VtnxmuG9i2kzB1IXK8PO9YEjZ3ayXf38w2M+RwYYbaOrG657cy7mmRt6ZE/xJMRma7eXWqbdhLdSkFYLsJ4M/ej4FQfGbFi4rMYbExmDUmnu0k9QealRB6eTIbOe6W24xNRl9magFkplR4O16CZ3rIR623Xi5Rod7Z/3eC9Owr55cEdLay8Zar9p6T+G+dljZRFTPe3+6Ehouz5GwwQAgFczkKeHQKGCH/vOqJXIEfk5+le0+hNRLG4bQqTXvtAVmSfboVH1zh5n0APzXLG7V5CNFgkHW54nE0Pzo1tQViyouT1RNXwWJGKWPjWdfKK+mqjbvWt6vET8jUk1hWWEN+0LH47qV4ZyZxsd2R0QeAx94B1+PGYWpayIl9uQtfH/oI8A0Mhh6MlGheDeMMli6yH3bpKJWC09fGRi2m1F3MIhKQFsubviurn5CKgsSz20Gy8RHFDN9ZdL3XzGM5jz/XfSAyVFsdeH5m/y493qcKJ5mpAVqC4NV45sCbB5lVuDu2Bg7W9yjToGNblQB1Y57NYdKZW6vl+DtEqT14Jmbyl7p2y3G8hs=
  app: nolabot1
  on:
    repo: geomin76/nolabot
